<? require_once(__DIR__ . "/Header.php"); ?>

<p align="center"><span style="color: #ffffff;"><span style="font-family: Arial, serif;"><span style="font-size: large;"><strong>Zens Individual Contributor License Agreement ("Agreement")</strong></span></span></span></p>
<p><span style="color: #ffffff;"><span style="font-family: Arial, serif;"><span style="font-size: medium;">Thank you for your interest in Zens ("Zens"). In order to clarify the intellectual property license granted with Contributions from any person or entity, Zens must have a Contributor License Agreement ("CLA") on file that has been signed by each Contributor, indicating agreement to the license terms below. This license is for your protection as a Contributor as well as the protection of Zens and its users; it does not change your rights to use your own Contributions for any other purpose.</span></span></span></p>
<p><span style="color: #ffffff;"><span style="font-family: Arial, serif;"><span style="font-size: medium;">You accept and agree to the following terms and conditions for Your present and future Contributions submitted to Zens. Except for the license granted herein to Zens and recipients of software distributed by Zens, You reserve all right, title, and interest in and to Your Contributions.</span></span></span></p>
<p><span style="color: #ffffff;"><span style="font-family: Arial, serif;"><span style="font-size: medium;"><strong>1. Definitions.</strong></span></span><span style="font-family: Arial, serif;"><span style="font-size: medium;">&nbsp;"You" (or "Your") shall mean the copyright owner or legal entity authorized by the copyright owner that is making this Agreement with Zens. For legal entities, the entity making a Contribution and all other entities that control, are controlled by, or are under common control with that entity are considered to be a single Contributor. For the purposes of this definition, "control" means (i) the power, direct or indirect, to cause the direction or management of such entity, whether by contract or otherwise, or (ii) ownership of fifty percent (50%) or more of the outstanding shares, or (iii) beneficial ownership of such entity. "Contribution" shall mean any original work of authorship, including any modifications or additions to an existing work, that is intentionally submitted by You to Zens for inclusion in, or documentation of, any of the products owned or managed by Zens (the "Work"). For the purposes of this definition, "submitted" means any form of electronic, verbal, or written communication sent to Zens or its representatives, including but not limited to communication on electronic mailing lists, source code control systems, and issue tracking systems that are managed by, or on behalf of, Zens for the purpose of discussing and improving the Work, but excluding communication that is conspicuously marked or otherwise designated in writing by You as "Not a Contribution."</span></span></span></p>
<p><span style="color: #ffffff;"><span style="font-family: Arial, serif;"><span style="font-size: medium;"><strong>2. Grant of Copyright License.</strong></span></span><span style="font-family: Arial, serif;"><span style="font-size: medium;">&nbsp;Subject to the terms and conditions of this Agreement, You hereby grant to Zens and to recipients of software distributed by Zens a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable copyright license to reproduce, prepare derivative works of, publicly display, publicly perform, sublicense, and distribute Your Contributions and such derivative works.</span></span></span></p>
<p><span style="color: #ffffff;"><span style="font-family: Arial, serif;"><span style="font-size: medium;"><strong>3. Grant of Patent License.</strong></span></span><span style="font-family: Arial, serif;"><span style="font-size: medium;">&nbsp;Subject to the terms and conditions of this Agreement, You hereby grant to Zens and to recipients of software distributed by Zens a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable (except as stated in this section) patent license to make, have made, use, offer to sell, sell, import, and otherwise transfer the Work, where such license applies only to those patent claims licensable by You that are necessarily infringed by Your Contribution(s) alone or by combination of Your Contribution(s) with the Work to which such Contribution(s) was submitted. If any entity institutes patent litigation against You or any other entity (including a cross-claim or counterclaim in a lawsuit) alleging that your Contribution, or the Work to which you have contributed, constitutes direct or contributory patent infringement, then any patent licenses granted to that entity under this Agreement for that Contribution or Work shall terminate as of the date such litigation is filed.</span></span></span></p>
<p><span style="color: #ffffff;"><a style="color: #ffffff;" name="_GoBack"></a> <span style="font-family: Arial, serif;"><span style="font-size: medium;"><strong>4.</strong></span></span><span style="font-family: Arial, serif;"><span style="font-size: medium;">&nbsp;</span></span><span style="font-family: Arial, serif;"><span style="font-size: medium;"><strong>Authorization.</strong></span></span><span style="font-family: Arial, serif;"><span style="font-size: medium;">&nbsp;You represent that you are legally entitled to grant the above license. If your employer(s) has rights to intellectual property that you create that includes your Contributions, you represent that you have received permission to make Contributions on behalf of that employer, that your employer has waived such rights for your Contributions to Zens, or that your employer has executed a separate Corporate CLA with Zens.</span></span></span></p>
<p><span style="color: #ffffff;"><span style="font-family: Arial, serif;"><span style="font-size: medium;"><strong>5. Original Creation.&nbsp;</strong></span></span><span style="font-family: Arial, serif;"><span style="font-size: medium;">You represent that each of Your Contributions is Your original creation (see section 7 for submissions on behalf of others). You represent that Your Contribution submissions include complete details of any third-party license or other restriction (including, but not limited to, related patents and trademarks) of which you are personally aware and which are associated with any part of Your Contributions.</span></span></span></p>
<p><span style="color: #ffffff;"><span style="font-family: Arial, serif;"><span style="font-size: medium;"><strong>6. No Support Obligation.</strong></span></span><span style="font-family: Arial, serif;"><span style="font-size: medium;">&nbsp;You are not expected to provide support for Your Contributions, except to the extent You desire to provide support. You may provide support for free, for a fee, or not at all. Unless required by applicable law or agreed to in writing, You provide Your Contributions on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied, including, without limitation, any warranties or conditions of TITLE, NON- INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A PARTICULAR PURPOSE.</span></span></span></p>
<p><span style="color: #ffffff;"><span style="font-family: Arial, serif;"><span style="font-size: medium;"><strong>7. Licensed Works.&nbsp;</strong></span></span><span style="font-family: Arial, serif;"><span style="font-size: medium;">Should You wish to submit work that is not Your original creation, You may submit it to Zens separately from any Contribution, identifying the complete details of its source and of any license or other restriction (including, but not limited to, related patents, trademarks, and license agreements) of which you are personally aware, and conspicuously marking the work as "Submitted on behalf of a third-party: [named here]".</span></span></span></p>
<p><span style="color: #ffffff;"><span style="font-family: Arial, serif;"><span style="font-size: medium;"><strong>8. Notification.</strong></span></span><span style="font-family: Arial, serif;"><span style="font-size: medium;">&nbsp;You agree to notify Zens of any facts or circumstances of which you become aware that would make these representations inaccurate in any respect.</span></span></span></p>
<p><br /> </p>


<? require_once(__DIR__ . "/Footer.php"); ?>